export const apiRoutes = {
  getTokenByPassword: "/api/getTokenByPassword",
  getProfile: "/api/getProfile",
  getTopProductsList: "/api/getTopProductsList",
  getNavMenu: "/api/getNavMenu",
  initialState: "/api/initialState",
  getCart: "/api/getCart",
  // getUserList: "/api/users",
  // getCarDetail: '/api/getCarDetail/:id',
  // getInsurance: '/api/getInsurance/:id',
  // job: '/api/job/:id?',
};

export const pageRoutes = {
  main: "/",
  about: "/about",
  bonus: "/bonus",
  delivery: "/delivery",
  guarantee: "/guarantee",
  services: "/services",
  blog: "/blog",
  contact: "/contacts",
  catalog: "/catalog",
  cart: "/cart",
  terms: "/terms-and-conditions",
  not_found: "/404",
  all: "*",
  auth: "/auth",
  // appointment: '/appointment/:id',
};
