import { ProductCardInterface } from "../interfaces/appointments";

export const products = [
  {
    id: 1,
    code: 100001,
    category: "coffee",
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
  {
    id: 2,
    code: 100002,
    category: "coffee",
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
  {
    id: 3,
    code: 100003,
    category: "tea",
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
  {
    id: 4,
    code: 100004,
    category: "tea",
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
  {
    id: 5,
    code: 100005,
    category: "coffee",
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
  {
    id: 6,
    code: 100006,
    category: "coffee",
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
  {
    id: 7,
    code: 100007,
    category: "coffee",
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
  {
    id: 8,
    code: 100008,
    category: "coffee",
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
  {
    id: 9,
    code: 100009,
    category: "coffee",
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
  {
    id: 10,
    code: 1000010,
    category: "coffee",
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
  {
    id: 11,
    code: 1000011,
    category: "coffee",
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
  {
    id: 12,
    code: 1000012,
    category: "coffee",
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
  {
    id: 13,
    code: 1000013,
    category: "coffee",
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
  {
    id: 14,
    code: 1000014,
    category: "coffee",
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
  {
    id: 15,
    code: 1000015,
    category: "coffee",
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
  {
    id: 16,
    code: 1000016,
    category: "coffee",
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
  {
    id: 17,
    code: 1000017,
    category: "coffee",
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
  {
    id: 18,
    code: 1000018,
    category: "coffee",
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
  {
    id: 19,
    code: 1000019,
    category: "coffee",
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
  {
    id: 20,
    code: 1000020,
    category: "coffee",
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
] as unknown as ProductCardInterface[];
