import { getRandomInt } from '../helpers/randomInt';
import {
TopProductCardInterface
} from '../interfaces/appointments'

export const topProducts = [
  {
    id: 1,
    code: `${getRandomInt(4000, 9999)}${getRandomInt(1000, 4000)}`,
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
  {
    id: 2,
    code: `${getRandomInt(4000, 9999)}${getRandomInt(1000, 4000)}`,
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
  {
    id: 3,
    code: `${getRandomInt(4000, 9999)}${getRandomInt(1000, 4000)}`,
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
  {
    id: 4,
    code: `${getRandomInt(4000, 9999)}${getRandomInt(1000, 4000)}`,
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
  {
    id: 5,
    code: `${getRandomInt(4000, 9999)}${getRandomInt(1000, 4000)}`,
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
  {
    id: 6,
    code: `${getRandomInt(4000, 9999)}${getRandomInt(1000, 4000)}`,
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
] as unknown as TopProductCardInterface[];