import {
TopProductCardInterface
} from '../interfaces/appointments'

export const topProducts = [
    {
      id: 0,
      name: "Il Rosso in grains",
      desc: "в зернах",
      sort: "Арабика: 80%",
      weight: 1,
      weightBox: 12,
      price: 900,
      imgUrl: "topProducts/nero.jpg",
      info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
      link: "",
    },
    {
      id: 1,
      name: "Il Rosso in grains",
      desc: "в зернах",
      sort: "Арабика: 80%",
      weight: 1,
      weightBox: 12,
      price: 900,
      imgUrl: "topProducts/nero.jpg",
      info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
      link: "",
    },
    {
      id: 2,
      name: "Il Rosso in grains",
      desc: "в зернах",
      sort: "Арабика: 80%",
      weight: 1,
      weightBox: 12,
      price: 900,
      imgUrl: "topProducts/nero.jpg",
      info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
      link: "",
    },
    {
      id: 3,
      name: "Il Rosso in grains",
      desc: "в зернах",
      sort: "Арабика: 80%",
      weight: 1,
      weightBox: 12,
      price: 900,
      imgUrl: "topProducts/nero.jpg",
      info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
      link: "",
    },
    {
      id: 4,
      name: "Il Rosso in grains",
      desc: "в зернах",
      sort: "Арабика: 80%",
      weight: 1,
      weightBox: 12,
      price: 900,
      imgUrl: "topProducts/nero.jpg",
      info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
      link: "",
    },
    {
      id: 5,
      name: "Il Rosso in grains",
      desc: "в зернах",
      sort: "Арабика: 80%",
      weight: 1,
      weightBox: 12,
      price: 900,
      imgUrl: "topProducts/nero.jpg",
      info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
      link: "",
    },
  ] as TopProductCardInterface[];