import { TopProductCardInterface } from "../interfaces/appointments";

export const topProducts = [
  {
    id: 1,
    code: 100001,
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
  {
    id: 2,
    code: 100002,
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
  {
    id: 3,
    code: 100003,
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
  {
    id: 4,
    code: 100004,
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
  {
    id: 5,
    code: 100005,
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
  {
    id: 6,
    code: 100006,
    name: "Il Rosso in grains",
    desc: "в зернах",
    sort: "Арабика: 80%",
    weight: 1,
    weightBox: 12,
    price: 900,
    imgUrl: "topProducts/nero.jpg",
    info: "елітна Арабіка з Центральної і Південної Америки і суміш високоякісної відбірної Робусти з найкращих областей Індії ",
    link: "",
  },
] as unknown as TopProductCardInterface[];
